version: "3"
services: 
    api:
        container_name: trimmr_api
        build: .
        ports: 
            - "5000:5000"
        volumes:
            - ./:/usr/src/app
        depends_on: 
            - db
        restart: always
        environment: 
            DB_URI: "mongodb://root:${TRIMMR_DB_PWD}@db:27017/trimmr?authSource=admin"
    
    db:
        container_name: trimmr_db
        image: mongo:4.0
        volumes: 
            - ./docker/mongo:/data/db
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "${TRIMMR_DB_PWD}"
            MONGO_INITDB_ROOT_DATABASE: "trimmr"